services:
  - type: web
    name: rag-demo
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    dockerCommand: uvicorn src.app.main:app --host 0.0.0.0 --port $PORT
    plan: starter
    region: oregon
    healthCheckPath: /docs
    envVars:
      - key: QDRANT_URL
        value: https://your-qdrant-instance.onrender.com
      - key: QDRANT_COLLECTION
        value: rag_documents
      - key: EMBEDDING_MODEL
        value: text-embedding-3-small
      - key: LLM_MODEL
        value: gpt-4o-mini
      - key: APP_HOST
        value: 0.0.0.0
      - key: APP_PORT
        value: $PORT
      - key: OPENAI_API_KEY
        sync: false  # Set this as a secret in Render dashboard
      - key: QDRANT_API_KEY
        sync: false  # Set this as a secret in Render dashboard
    autoDeploy: true
    branch: main
