apiVersion: v1
kind: ConfigMap
metadata:
  name: rag-demo-config
  namespace: rag-demo
data:
  QDRANT_URL: "http://qdrant-service:6333"
  QDRANT_COLLECTION: "rag_documents"
  EMBEDDING_MODEL: "text-embedding-3-small"
  LLM_MODEL: "gpt-4o-mini"
  APP_HOST: "0.0.0.0"
  APP_PORT: "8080"
