apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  name: rag-demo-cluster
  namespace: default
spec:
  location: us-central1-a
  initialNodeCount: 1
  minMasterVersion: "1.28"
  nodeConfig:
    machineType: e2-medium
    diskSizeGb: 20
    diskType: pd-standard
    imageType: COS_CONTAINERD
    oauthScopes:
    - https://www.googleapis.com/auth/cloud-platform
    metadata:
      disable-legacy-endpoints: "true"
    workloadMetadataConfig:
      mode: GKE_METADATA
  addonsConfig:
    horizontalPodAutoscaling:
      disabled: false
    httpLoadBalancing:
      disabled: false
  networkPolicy:
    enabled: true
  privateClusterConfig:
    enablePrivateNodes: true
    enablePrivateEndpoint: false
  masterAuthorizedNetworksConfig:
    enabled: true
    cidrBlocks:
    - cidrBlock: "0.0.0.0/0"
      displayName: "All"
